-- ============================================================
-- Keurzen — Weekly AI Reports
--
-- Stores AI-generated weekly household reports.
-- Generated by generate-weekly-report Edge Function using Claude Haiku.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.weekly_reports (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  household_id    UUID NOT NULL REFERENCES public.households(id) ON DELETE CASCADE,
  week_start      DATE NOT NULL,
  summary         TEXT NOT NULL,
  attention_points JSONB NOT NULL DEFAULT '[]'::jsonb,
  insights        JSONB NOT NULL DEFAULT '[]'::jsonb,
  orientations    JSONB NOT NULL DEFAULT '[]'::jsonb,
  model           TEXT NOT NULL,
  generated_at    TIMESTAMPTZ NOT NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(household_id, week_start)
);

CREATE INDEX IF NOT EXISTS idx_weekly_reports_household_week
  ON public.weekly_reports (household_id, week_start DESC);

-- ─── RLS : weekly_reports ───────────────────────────────────────────────────

ALTER TABLE public.weekly_reports ENABLE ROW LEVEL SECURITY;

-- Members can read their household's reports
DROP POLICY IF EXISTS "members_can_view_reports" ON public.weekly_reports;
CREATE POLICY "members_can_view_reports" ON public.weekly_reports
  FOR SELECT USING (
    EXISTS (
      SELECT 1 FROM public.household_members hm
      WHERE hm.household_id = weekly_reports.household_id
        AND hm.user_id = auth.uid()
    )
  );

-- No INSERT/UPDATE/DELETE policies — only service_role writes
